### ISSUE TITLE
Friend names are empty strings

### ISSUE THREAD

**Issue by onbjerg** [saneki/node-toxcore#11]
```js
tox.on('friendName', function(e) {
      console.log(tox.getFriendNameSync(e.friend()));
});
```

yields an empty string. Always.

**Comment by onbjerg** [comment]
Forgive me. Appearantly it only does this once. ``e.name()`` yields a non-empty string.

**Comment by saneki** [comment]
This is probably due to libtoxcore not having received the friend name yet (first friendName event for that friend), in which case it would make sense for getFriendNameSync to return empty as all callbacks run before libtoxcore actually sets the current friend name to the received friend name. It probably does this in case any callbacks want to use getFriendNameSync to obtain the previous friend name.

**Comment by onbjerg** [comment]
Oh, that makes sense.
